apiVersion: v1
kind: Service
metadata:
  name: usi-csv-service
  labels:
    run: usi-csv
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6868
  selector:
    run: usi-csv
